/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://6wp3e6r45bfdff2u36icdmkwza.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3fogdzgapvb7hgwldm3ep2vmya",
    "aws_cognito_identity_pool_id": "us-west-2:3177a0a0-f769-49c2-aeda-2bd92b477cf0",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_BkuxlB0tI",
    "aws_user_pools_web_client_id": "1ohidmdvqa65in2kk1ote424ri",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "PREFERRED_USERNAME",
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "spotlookc87e62bd84c04be2a48d17b52655721440927-staging",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
